[package]
name = "esa-nippou"
version = "1.0.2"
authors = ["mizukmb <mizukmb6@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.31.2"
reqwest = "0.9"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"
rpassword = "2.0"
dirs = "1.0.4"
failure = "0.1.5"